name: Backend - Rust Build and Release

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: moonrepo/setup-rust@v1
      with:
        profile: minimal

    - name: Build Rust Project
      run: |
        cd backend
        cargo build --release

    - name: Compress as tar.gz
      run: tar -czvf group-3-ecommerce-product-module.tar.gz -C backend/target/release/group-3-ecommerce-product-module

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: group-3-ecommerce-product-module
        path: ./group-3-ecommerce-product-module.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: group-3-ecommerce-product-module
        path: .

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false
    
    - name: Upload Release Asset
      run: gh release upload ${{ github.run_number }} ./group-3-ecommerce-product-module.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy Backend
      run: curl -X GET http://172.105.25.146:8082/backend/deploy/${{ github.run_number }}
